INSERT INTO USER_SDO_GEOM_METADATA VALUES('GEO_LOG','THE_GEOM',SDO_DIM_ARRAY(SDO_DIM_ELEMENT('LONGITUDE',-180,180,0.00001), SDO_DIM_ELEMENT('LATITUDE',-90,90,0.00001)),4326);

CREATE INDEX geo_log_the_geom_idx ON GEO_LOG(THE_GEOM) INDEXTYPE IS mdsys.spatial_index;